<?php

declare(strict_types=1);
/**
 * This file is part of Hapi.
 *
 * @link     https://www.nasus.top
 * @document https://wiki.nasus.top
 * @contact  xupengfei@xupengfei.net
 * @license  https://github.com/nasustop/hapi-queue/blob/master/LICENSE
 */
namespace Nasustop\HapiQueue\Amqp;

use Hyperf\Amqp\Message\ConsumerMessageInterface;
use Nasustop\HapiQueue\Job\JobInterface;
use PhpAmqpLib\Message\AMQPMessage;

class Consumer extends \Hyperf\Amqp\Consumer
{
    /**
     * set Factory.
     */
    public function setFactory(ConnectionFactory $factory): self
    {
        $this->factory = $factory;

        return $this;
    }

    /**
     * get Factory.
     */
    public function getFactory(): \Hyperf\Amqp\ConnectionFactory
    {
        return $this->factory;
    }

    protected function getCallback(ConsumerMessageInterface $consumerMessage, AMQPMessage $message): callable
    {
        $job = $consumerMessage->unserialize($message->getBody());
        if ($job instanceof JobInterface) {
            $consumerMessage->setPayload($job);
        }
        return parent::getCallback($consumerMessage, $message); // TODO: Change the autogenerated stub
    }
}
